server:
  port: 8100
  servlet:
    context-path: /auth
spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:authDB
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
jwt:
  secret: h4f8093h4f983yhrt9834hr0934hf0hf493g493gf438rh438th34g34g
  lifetime: 36000000

