server:
  port: 8199
  servlet:
    context-path: /cart

integrations:
  core-service:
    url: http://localhost:8189/core/
    connect-timeout: 5000
    read-timeout: 10000
    write-timeout: 5000
#    вот он redis
spring:
  data:
    redis:
      host: localhost
      port: 6379
      password: pass
