server:
  port: 8081
  servlet:
    context-path: /core
spring:
  datasource:
    driver-class-name: org.h2.Driver
    username: sa
    password:
    url: jdbc:h2:mem:db;MODE=PostgreSQL;
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: false
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect